/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model({ ...props }) {
  const group = useRef()
  const { nodes, materials } = useGLTF('/assets/models/magic-gate.gltf')
  return (
    <group ref={group} {...props} dispose={null}>
      <group position={[1.37, 15.08, 2.63]} rotation={[-Math.PI / 2, 0.25, -Math.PI / 2]} scale={[0.39, 1.29, 1.29]}>
        <mesh geometry={nodes.Cube002_0.geometry} material={materials.gate_stone_01} />
        <mesh geometry={nodes.Cube002_1.geometry} material={materials.gate_stone_02} />
        <mesh geometry={nodes.Cube002_2.geometry} material={materials.gate_stone_03} />
        <mesh geometry={nodes.Cube002_3.geometry} material={materials.gate_steel_01} />
        <mesh geometry={nodes.Cube002_4.geometry} material={materials.gate_steel_02} />
        <mesh geometry={nodes.Cube002_5.geometry} material={materials.gate_wood_01} />
        <mesh geometry={nodes.Cube002_6.geometry} material={materials.gate_wood_02} />
      </group>
      <group position={[-0.05, -0.04, -4.05]} rotation={[0, 0, -Math.PI / 2]} scale={[1, 1, 0.54]}>
        <mesh geometry={nodes.Cylinder000_0.geometry} material={materials.gate_blue_light} />
      </group>
    </group>
  )
}

useGLTF.preload('/assets/models/magic-gate.gltf')
